apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helios-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dograchaitanya20/helios-gitops.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: helios
  syncPolicy:
    automated:
      prune: true      # remove resources deleted from git
      selfHeal: true   # revert manual kubectl edits back to git state — this IS GitOps
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
