apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helios
resources:
  - ../../base
patches:
  - path: replica-patch.yaml
images:
  - name: ghcr.io/dograchaitanya20/helios-gitops/helios-api
    newTag: 67de502
