apiVersion: v1
kind: Service
metadata:
  name: helios-api
  labels:
    app: helios-api
spec:
  selector:
    app: helios-api
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
