apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helios-staging
resources:
  - ../../base
images:
  - name: ghcr.io/dograchaitanya20/helios-gitops/helios-api
    newTag: latest
